services:
  database_mongoDB:
    image: mongo
    container_name: MONGO_DB
    networks:
      - app_network
    ports:
      - ${DB_PORT}:27017
    volumes:
      - ./database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
networks:
  app_network:
    driver: bridge